apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: __ServiceName__
  labels:
    app: __ServiceName__
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: __ServiceName__
    spec:
      containers:
      - name: __ServiceName__
        image: __ContainerImage__:__Release__
        imagePullPolicy: Always
        ports:
        - containerPort: __AppPort__
#        env:
#        - name: PORT
#          value: __AppPort__
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: __AppPort__
#        readinessProbe:
#          httpGet:
#            path: /readyz
#            port: __AppPort__
        resources:
          limits:
            cpu: 10m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
      terminationGracePeriodSeconds: 30
