apiVersion: v1
kind: Service
metadata:
  name: {{ .ServiceName }}
  labels:
    app: {{ .ServiceName }}
spec:
  ports:
  - port: {{ .ServicePort }}
    targetPort: {{ .AppPort }}
    protocol: TCP
    name: http2
  selector:
    app: {{ .ServiceName }}
